apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: djangopoll
    tier: frontend
  name: djpoll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangopoll
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: djangopoll
        tier: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: 5ak3t/django-kube:v1
        name: djpoll
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
status: {}
