apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: djangopoll
    tier: frontend
  name: djpoll
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: djangopoll
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
